"""Generate the parser's semicolon-terminated WHATWG entity table."""

from __future__ import annotations

import json
import sys
from pathlib import Path


def rust_string(value: str) -> str:
    escaped = []
    for character in value:
        if character == "\\":
            escaped.append("\\\\")
        elif character == '"':
            escaped.append('\\"')
        elif " " <= character <= "~":
            escaped.append(character)
        else:
            escaped.append(f"\\u{{{ord(character):x}}}")
    return f'"{"".join(escaped)}"'


def main() -> None:
    source = Path(sys.argv[1])
    destination = Path(sys.argv[2])
    entities = json.loads(source.read_text(encoding="utf-8"))
    rows = sorted(
        (name[1:-1], record["characters"])
        for name, record in entities.items()
        if name.endswith(";")
    )

    lines = [
        "// @generated by tools/generate_entities.py from the WHATWG entities.json.",
        "// Only semicolon-terminated names are included, as required by CommonMark.",
        "",
        "pub(super) static NAMED_REFERENCES: &[(&str, &str)] = &[",
    ]
    lines.extend(
        f"    ({rust_string(name)}, {rust_string(value)})," for name, value in rows
    )
    lines.extend(
        [
            "];",
            "",
            "pub(super) fn lookup(name: &str) -> Option<&'static str> {",
            "    NAMED_REFERENCES",
            "        .binary_search_by_key(&name, |(name, _)| *name)",
            "        .ok()",
            "        .map(|index| NAMED_REFERENCES[index].1)",
            "}",
            "",
        ]
    )
    destination.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
