#!/usr/bin/env python3
"""PreToolUse hook: block hand-edits to the generated entity table."""
import json
import sys

GUARDED_SUFFIX = "crates/context-parser/src/inline/entities.rs"


def main() -> None:
    data = json.load(sys.stdin)
    file_path = data.get("tool_input", {}).get("file_path", "").replace("\\", "/")

    if file_path.endswith(GUARDED_SUFFIX):
        print(
            json.dumps(
                {
                    "hookSpecificOutput": {
                        "hookEventName": "PreToolUse",
                        "permissionDecision": "deny",
                        "permissionDecisionReason": (
                            "src/inline/entities.rs is generated by "
                            "tools/generate_entities.py — rerun that script instead of "
                            "hand-editing the generated table."
                        ),
                    }
                }
            )
        )

    sys.exit(0)


if __name__ == "__main__":
    main()
